services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: travel-app
    restart: always
    volumes:
      - .:/app
    ports:
      - "8087:8087"
    command: bash -c "chmod +x /app/migrate && /app/migrate && /app/entrypoint"
    # depends_on:
    #   - db
    env_file:
      - ./.env

#   db:
#     image: postgres:14
#     container_name: postgres-travel
#     environment:
#       POSTGRES_DB: ${DB_NAME}
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#     volumes:
#       - db_data:/var/lib/postgresql/data
#     ports:
#       - "5434:5432"
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
#       interval: 2s
#       retries: 10

# volumes:
#   db_data:
